/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlogContentHeader: typeof import('./../components/blog/BlogContentHeader.vue')['default']
    BlogList: typeof import('./../components/blog/BlogList.vue')['default']
    BlogPress: typeof import('./../components/BlogPress.vue')['default']
    BlogSearch: typeof import('./../components/blog/BlogSearch.vue')['default']
    Content: typeof Content
    FooterBox: typeof import('./../components/footer/FooterBox.vue')['default']
    HeaderBox: typeof import('./../components/header/HeaderBox.vue')['default']
    HeaderItem: typeof import('./../components/header/HeaderItem.vue')['default']
    HeaderMenuList: typeof import('./../components/header/HeaderMenuList.vue')['default']
    Icon: typeof Icon
    LogoBasicLogo: typeof import('./../components/header/LogoBasicLogo.vue')['default']
    MainPress: typeof import('./../components/MainPress.vue')['default']
    NotFound: typeof import('./../components/NotFound.vue')['default']
    RecordBackground: typeof import('./../components/RecordBackground.vue')['default']
    TRexRunner: typeof import('./../components/TRexRunner.vue')['default']
  }
}
